os:
  - linux

dist: xenial

sudo: required

services:
  - docker

language: node_js
node_js:
  - "10"

before_install:
# yarn is outdated on Linux images
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
    export PATH=$HOME/.yarn/bin:$PATH
  fi

before_script:
# Make variables and function from Travis available in our script
# See implementation https://github.com/travis-ci/travis-build/blob/4041ba116ddb3bdfd66ab8acbb7094dee28d6797/lib/travis/build/templates/header.sh
# and http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
- export ANSI_CLEAR
- export -f travis_nanoseconds travis_fold travis_time_start travis_time_finish

script:
- ./travis.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/

notifications:
  email: false
